const {print, trace, hint, $} = require('./index.js')
test('print', () => {expect(print('Neelesh Vaikhary')).toBe('Neelesh Vaikhary')})
test('trace', () => {expect(trace('Trace')(true)).toBe(true)})
test('hint', () => {expect(hint('Hint')(true)).toBe(true)})
test('$', () => {expect($(hint('Hinting'),trace('Tracing...'),print)('Neelesh')).toBe('Neelesh')})
